### ISSUE TITLE
wstool scrape should skip nested workspace

### ISSUE THREAD

**Issue by jayvdb** [vcstools/wstool#108]
I'm not sure whether nested workspaces are acceptable or not, but I have the following layout

* `.rosinstall`
* `foo/.rosinstall`
* `foo/bar/.git`
* `baz/.git`

I expect `wstool scrape` to find `baz` , but skip `foo/*` , maybe with a comment.  Or if nested workspaces are a really bad idea, it should emit a warning.

**Comment by tkruse** [comment]
In general nesting rosinstall folders inside each other is not anything the tools have been concerned with, because the .rosintall file explicitly declares what folders are inside/outside the workspace.

So users nesting such folders is not an issue in itself.

However it is somewhat unintuitive, a workspace folder containing other workspace folders without any recursion supported by a tool, so I don't think this is a pattern to be encouraged.

I don't think anyone considered this when scrape was added (was ticket #26). I don't think many users use scrape to begin with, and even less will have this situation. So we could consider the current specification as undefined, and define one for future versions.

If you have some good reason to nest workspace folders that you want to share, that could help in the decision making. 

I'd say
+0 for skipping nested
-0 for making non-skipping a defined / documented behavior
+0 for emitting some warning in scrape

So if you implement a PR, probably would be merged.
Scrape is implemented ad bottom here:
https://github.com/vcstools/wstool/blob/master/src/wstool/multiproject_cli.py

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
