### ISSUE TITLE
shallow Option in .rosinstall Files

### ISSUE THREAD

**Issue by JWhitleyWork** [vcstools/wstool#123]
Looking at the code in src/wstool, it looks like all operations that involve a call to `cmd_install_or_update` should be able to pass the `shallow` flag (not just `cmd_init` as is implemented now). Having `--shallow` implemented on init makes sense and is a blanket command which only applies to git repositories (Mercurial doesn't support shallow clones). However, because online tools such as [ROS industrial_ci](https://github.com/ros-industrial/industrial_ci/) only support merging existing .rosinstall files for a workspace and we have no control over the init command, the option to do a shallow clone on a per-config-entry basis would be a huge boon.

My major question is: How do the maintainers want this implemented? I'm happy to make a PR but, should I:

* Create a new VCS type (something like `git-shallow`)?
* Add an additional key that is only supported when the VCS type is `git`?
* Add something akin to `setup-file` like `vcs-config`?

What's the preference here?

**EDIT**: Or, should I just modify `industrial_ci` to accept a flag that sets `init --shallow` when creating the workspace?

**Comment by 130s** [comment]
+1 for the idea. I'm stuck at a project that clones by `wstool` on CI a large amount of data via `git` (despite yes it's debatable whether large amount of data should be stored on a git repo) and the large data seems to be causing an issue so my team is curious to limit the git history to be cloned.

I think each repo in the `.rosinstall/.repos` file should be treated differently regarding this feature? E.g. for some repos you want the full history while for other repos you only want to limited history. So user's control should be done in .rosinstall/.repos file (instead of an argument to `wstool` command). This means the file format change, but by making it optional, hope it can be done in a backward compatible way.

As for where the code change to be made, I see a `GitClient` class in [vcstools/vcstools/git.py](https://github.com/vcstools/vcstools/blob/2cdf20fd1f82bd6057aab80957618e749ea73ee2/src/vcstools/git.py) that is imported by `wstool`. That may be one location to look at?

**Comment by 130s** [comment]
@JWhitleyAStuff Are you still planning to provide a PR? If not my team might be interested in working on that.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
