### ISSUE TITLE
best way to modify all repos in a workspace? 

### ISSUE THREAD

**Issue by dustingooding** [vcstools/wstool#29]
What's the best approach to, say, switch all repos in a workspace to a different branch if that branch exists?  For example, 10 repos in my workspace are on 'master'.  But I'm working on a new feature that affects multiple repos.  I'd like to switch back and forth between my master branch and feature branch(es) easily without having to go to each repo root and "git checkout".

vcs-custom allows for this (in a way) by using 'vcs custom --args checkout myBranch".

(Also, if there's a more appropriate way to ask questions or suggest new features, I'll be glad to do that instead.)

**Comment by wkentaro** [comment]
The `ws-each` command is easy to implement even if without wstool's subcommand (by using `wstool info --only=localname,scmtype,path`, `grep`, `awk`), but I think adding the command is a good idea to enhance wstool as a workspace managing tool.

I'm thinking the command will be something like `git submodule foreach 'git pull origin master'`.
And enabling to assign repository in workspace is good idea like `wstool ws-each repo0 repo2 'git pull origin master'`. (but in this case, `ws-each` may be inappropriate, I prefer `foreach`)

Do you have any idea? about
* implementing this kind of command
* name of the command

(Maybe I will have time to help to implement this feature after my project in next month.)

**Comment by wkentaro** [comment]
I moved from: https://github.com/vcstools/wstool/pull/38#issuecomment-125135862

**Comment by tkruse** [comment]
For the name and structure, I like ```wstool foreach [--bzr] [--git] [--hg] [--svn] [repository]+```
On the wstool side, this could be largely copy&paste of the status command (see multiproject_cmd:cmd_status()).

Since we have shell command execution in vcstools, I can imagine reusing that, so the worked in cmd_foreach() could directly invoke vcstools.common:run_shell_command(...)

All of the arguments to run_shell_command might also be arguments to foreach, so maybe foreach would become:
```
wstool foreach [--bzr] [--git] [--hg] [--svn] [repository]+ [--shell] [--us] [--hide-stdout] [--timeout=double] [..no-filter]
```

I believe verbose must be set to true, and no_warn seems to be an obsolete argument. Some refactoring might be possible in vcstools.py, because the verbose argument and the _discard_line() functions are specific to vcs commands (and also evil).

**Comment by wkentaro** [comment]
So the todo list becomes like below?

- [ ] 1. refactor vcstools in particular: run_shell_command(), _discard_line()
- [ ] 2. Add cmd_foreach() to wstool

regarding run_shell_command() arguments, I'm thinking like below:

* `no_warn` arg is not used in run_shell_command
* always `shell=False` for security (according to: https://docs.python.org/2/library/subprocess.html#using-the-subprocess-module)
* always `verbose=True` so does not care about `show_stdout` because `verbose` overwrites (so  refactoring _discard_line() is probably not required)
* `--quiet` option for `no_filter=True` otherwise `no_filter=False`
* `--timeout=double` for `timeout=double` otherwise `timeout=None`
* always `us_env=False` to get users' expected outputs

so the foreach's options will be 
`wstool foreach [--bzr] [--git] [--hg] [--svn] [repository]+ [--quiet] [--timeout=double] 'command'`

What do you think about above?

**Comment by tkruse** [comment]
refactoring vcstools is optional, it is a bit dirty, but can be used as is with ```verbose=True```, I think. Also this should not be refactored too much, as this is the most important part of vcstools which must not break (else ROS installation is broken).

I removed no_warn in the other branch by now.
I think most of your assumptions are reasonable, but if run_shell_command() has the options it has, it should be for good reason (we ran into problems without the options). 

So it is quite possible users will have similar problems for their commands as we had for our commands, and would be happy to have those options (in particular shell and us_env).

**Comment by wkentaro** [comment]
Now I think the foreach command is easily created with function in shell like below.
And in most cases, this works, so maybe no need to create new subcommand at this point.

```
# bash

wstool_foreach () {
  local -a locations
  local e
  locations=$(wstool info --only=path)
  pushd `pwd` >/dev/null
  for e in $locations; do
    cd $e
    eval $@
  done
  popd >/dev/null
}

wstool () {
  case "$1" in
    (foreach)
      shift; wstool_foreach $@
      ;;
    (*)
      command wstool $@
      ;;
  esac
}
```

now I can run
```
$ wstool foreach "[ -d .git ] && git pull origin master"
```

**Comment by tkruse** [comment]
going through bash is an clean and easy solution, the only small problem is that we cannot nicely put foreach into the tool "--help" that way. However we could put it into --help as extra text, and deliver it with the autocomplete functions. I am undecided whether to do so.

**Comment by wkentaro** [comment]
yeah, I mean this can be configured at shell of users who like this subcommand, and wstool officially does not support this.

**Comment by wkentaro** [comment]
I personally rethought this command is useful enough to be supported officially.
So sent PR #55 .

**Comment by wkentaro** [comment]
#55 is merged. So please close. (maybe the auto closing was not triggered because of some syntax difference)

**Comment by wjwwood** [comment]
Thanks for reminding us.
