### ISSUE TITLE
duplicating a local workspace with wstool - not working ?

### ISSUE THREAD

**Issue by asmodehn** [vcstools/wstool#36]
I am trying to duplicate a workspace on my local machine, but I am encountering unexpected errors...

Lets say I have a workspace at ~/my_workspace
I instructed wstool to init and fill up a .rosinstall file at ~/my_workspace/src/.rosinstall.
I do a lot of work...

Now, I want to duplicate that workspace to another location, without taking my local modifications.
I was expecting this to work, but it seems it doesnt :
```
mkdir -p ~/my_new_workspace/src
cd ~/my_new_workspace/src
wstool init
wstool merge ../../my_workspace/src/.rosinstall
```
And I get something like :
```
ERROR in config: Forbidden non-SCM element: ../../my_workspace/src/<first_local_name>
```

However this does work ( hacky ? ) : 
```
mkdir -p ~/my_new_workspace/src
cp ../../my_workspace/src/.rosinstall ~/my_new_workspace/src
cd ~/my_new_workspace/src
wstool update
```

So is there a bug in wstool when using local rosinstall files ?

**Comment by tkruse** [comment]
Hello Alex,
thanks for reporting this. 

copy&pasting .rosinstall files is not hacky, the rosinstall files were designed to make that work.

The merge command was not intended for what you want to use it. The general problem here is for the tool to guess your intention. If your old workspace has an element at 

```
~/old_workspace/src/foo
```

and you want to merge the .rosintall in 

```
~/my_new_workspace/src
```

should the new entry be:
```~/old_workspace/src/foo``` or ```~/my_new_workspace/src/foo```? I understand in this case you wanted the latter to happen, but traditionally (with rosws and rosinstall), the first thing would happen. Yet because it is a bad idea to have two workspaces to issue commands on the same folder, the merge command strips away vcs information (again this was for rosinstall and rosws). With wstool, entries without vcs information make no sense, hence the error.

I think that behavior does not make much sense with wstool, so the behavior of merge in wstool should be changed with respect to local files. However I am not sure how best to change it, it would require some thought. I would not call this a bug, but it surely is confusing (and useless) behavior. 

I'll let William decide, but I would suggest closing this bug and opening a new one to modify wstool behavior when calling ```wstool merge path/to/local_rosinstall(folder)``` or  ```wstool init target path/to/local_rosinstall(folder)```

**Comment by tkruse** [comment]
Actually, the following should also work:

```cat ~/old_workspace/src/.rosinstall | wstool merge -```

Where the tool input is not a file(location), but individual entries, thus no ambiguity over what to do with them. THis would also do any merge interaction.
