### ISSUE TITLE
new feature: locate repositories with regular expression in wstool update

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#46]
I think `wstool update` can be enhanced with regular expression for locating repositories in workspace.
the behavior will be like:
```
% wstool update vcstools/*
[vcstools/wstool] Updating /Users/ken/ws/vcstools/wstool
[vcstools/wstool] Done.
[vcstools/vcstools] Updating /Users/ken/ws/vcstools/vcstools
[vcstools/vcstools] Done.

% cd vcstools/wstool

% wstool update ../*
[vcstools/wstool] Updating /Users/ken/ws/vcstools/wstool
[vcstools/wstool] Done.
[vcstools/vcstools] Updating /Users/ken/ws/vcstools/vcstools
[vcstools/vcstools] Done.
```

**Comment by tkruse** [comment]
We had the same idea for rosws: https://github.com/vcstools/rosinstall/issues/4
But features like this do not help users very often, and they make the code more complex, allowing for more bugs. So I would say -0

**Comment by tkruse** [comment]
Also note that even without your PR; bash does some of this using globbing.

**Comment by wkentaro** [comment]
the case when I want this feature is:

1. After `wstool set longusername/longreponame https://github.com/longusername/longreponame.git`, typing again the long local name with `wstool update` is disgusting. I wanna do `wstool update long*`.
2. In very large workspace which have a lot of repos, I'd like to do update only repos which are changed frequently.

1 may be satisfied after completion(#32) is supported, but does not work when there are repos whose name is similar.
2 is satisfied with shell globbing `wstool update $(echo ros_visualization/*)`. (I didn't know about that feature of bash, thanks) But it works with limited expression and need to change dir to workspace root because it works only for dir path from there.

I still think this feature can be useful even only wildcard not regex. The `wstool update` takes time in large workspace so I usually would like to limit repos which is updated easily.

If you concern about bugs, why not add this feature with `--regex` option?
(and if you don't think this feature should be added at present, please remain this with untargeted label..)

**Comment by tkruse** [comment]
I am mostly concerned about bugs for the maintainer side, not the user side. The whole ROS ecosystem has far too few maintainers to support all the tools/packages. I am happy that vcstools and wstools had relatively few bugs discovered over the last two years. Keeping certain features out of tools means the maintainers have more time for their real jobs or other bugs.

So usually when considering new features that help users save time, I think about how often users would benefit from it. If a user uses a command 10 times every day, making that command easier to use is probably worth it. If the user only uses a command once a month, then it does not matter if t is rather painful.

An alternative to what you want for use-case 1 might be to have a --update option in the wstool set command, such that wstool automatically runs update after set. I cannot remember if I ever considered that.

Helping use-case 2 might be a bash command to go to the top of the workspace, which is what roscd did in rosbuild workspaces. regular expressions are a problem because users easily confuse them with globbing. In particular when forgetting hyphens, the bash will apply globbing if something matches, else pass unglobbed arguments, which can confuse users a lot. I don't know many command-line tools that would support regexes in their arguments other than tools which are all about string manipulation like sed or grep. So I think it is a best practice for command line tools not to support any regex magic in general.

**Comment by wkentaro** [comment]
I understood your concern, thanks. so closing this issue.
