### ISSUE TITLE
Speedup CI by doing shallow clones

### ISSUE THREAD

**Issue by davetcoleman** [vcstools/wstool#96]
wstool seems to lack the ability to only download the latest code in a git repo, e.g.:

```
git clone --depth 1 https://github.com/jquery/jquery.git jquery
```

Seems like this should be a command-line option for `wstool update`. This should greatly improve download time for many repos with long histories.

**Comment by tkruse** [comment]
indeed, the underlying vcstools has such an option for checkouts, but it is not immediately obvious how to make good use of it from wstool.

The core of the problem is that wstool is a tool intended to create a workspace for developers, allowing to switch branches, going back in time and such. It is not intended as a script to fetch data for one-time usage. If there were enough demand for such use-cases, it would probably be more reasonable to create a separate command for that.
But given the vcstool exist, I guess the ROS community would not benefit much from such an effort. 

Pull requests still welcome, though, I guess.

**Comment by davetcoleman** [comment]
This would be a great benefit for continuous integration, which does not care about the history of the repo...

**Comment by tkruse** [comment]
Both vcstools and wstool may also be used as libraries, I can imagine a simple script for fetching all of a rosinstall file could be done n 20 lines of python. Maybe I'll find some time to post this.

**Comment by tkruse** [comment]
oh, actually, there is rosco: https://github.com/vcstools/rosinstall/blob/master/scripts/rosco, in the rosinstall package. Just let it accept a parameter "shallow" and pass it to the checkout function (and through to vcstools.vcs_client. I had forgotten all about that one. Should be an easy PR; if the scripts still run through (they might not if they do integration tests against very old ROS distros).

**Comment by tkruse** [comment]
See my PR vcstools/rosinstall#105

**Comment by at-wat** [comment]
I think the shallow option is still useful for development.
Current git can perform commit/push/pull on shallow copied repositories and also unshallow is supported.
In my case, cloning large system to make a clean copy at outdoor fields by using mobile network was sometimes needed, and it was pretty troublesome.

I have opened PR for it.
